### ISSUE TITLE
UI: Overview

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#15]
![1_overview](https://cloud.githubusercontent.com/assets/5836089/6162610/6726b7a0-b286-11e4-862d-4ced7ac1a415.png)
- [x] 1) The container size should be similar, so that everything is "in line".

**Comment by zathras-crypto** [comment]
How about https://github.com/zathras-crypto/mastercore/commit/6a79cf97510c88867afa6a3c85a9f8dcf7eb06ef?

**Comment by dexX7** [comment]
Perfect!

**Comment by dexX7** [comment]
Going to close, because it's done and there are too many issues. Please continue to use tags, maybe even get a plain "0.0.9.1" tag, so it's possible to search like this:

https://github.com/zathras-crypto/mastercore/issues?q=label%3A"improvement+-+0.0.9.1"

At the end,  it would be great, if we see "all this was done in 0.0.9.1". :)
