### ISSUE TITLE
UI: multiple incoming STO result in one history entry

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#27]
When more than one address in the wallet receives tokens from a "send to owner" transaction, then only one entry with the combined amount _(need double check)_ is created.

**Comment by zathras-crypto** [comment]
Hmm, is this a problem?  The logic I've used is that each row in the history is a transaction - if you had say 10 addresses that received a cut of an STO, should we be showing that as ten separate entries?

**Comment by zathras-crypto** [comment]
Note if you double click the STO transaction in history, do you see the breakdown?
![image](https://cloud.githubusercontent.com/assets/5633351/6208479/caf69cda-b60c-11e4-8f31-2da1979727ca.png)

**Comment by dexX7** [comment]
IIRC (not in the right OS atm) it works under the hood perfectly fine, and every receiver gets what he should.

**Comment by dexX7** [comment]
Confirmed, it includes all recipients in the details tab.

**Comment by zathras-crypto** [comment]
So what's your perspective on the UX for this mate?  Especially for the sake of 0.0.9.1 expediency I'd like to keep it as is (1 transaction per row).

**Comment by dexX7** [comment]
No high priority. Maybe, depending on the work to do so, it could show "multiple" (or so) instead of an address, in the case of a multi-recipient-STO?

**Comment by zathras-crypto** [comment]
I like that idea, should be fairly simple :) Leave it with me

**Comment by zathras-crypto** [comment]
![image](https://cloud.githubusercontent.com/assets/5633351/6221542/22a49b3a-b699-11e4-95b5-408bc3f71cce.png)

https://github.com/zathras-crypto/mastercore/commit/54078198790a4e4c12336c10f256a79a22bbcf5d

**Comment by zathras-crypto** [comment]
I'm a dumbass :( optimized here https://github.com/zathras-crypto/mastercore/commit/a8919979f083899d251d053b1dad372ca55025bb (forgot that I'd made getRecipients filter on wallet already by default, so no need to do a second time).

Thanks
Z

**Comment by dexX7** [comment]
I completely missed this one earlier. Test starting in a few minutes.

**Comment by dexX7** [comment]
Works well.
