### ISSUE TITLE
UI: overview doesn't refresh after unconfirmed send

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#28]
In contrast to the balance and send tab, the overview tab does not refresh after sending tokens via the UI, but only after a block is mined.

**Comment by zathras-crypto** [comment]
Be back in an hour or so mate - re overview any outbound send should be a
change of bitcoin balance and thus trigger the balancesUpdated signal no?

**Comment by dexX7** [comment]
Ah, I found it: it was only subscribed to `refreshOmniState`, but no longer to `balanceChanged`.

**Comment by zathras-crypto** [comment]
https://github.com/zathras-crypto/mastercore/commit/8ba72ca1ec3ed2fbaf33b8dba8518efad8426f25?

**Comment by zathras-crypto** [comment]
NVM I think you corrected this in your PR?

**Comment by dexX7** [comment]
I addressed it in my PR.

I'm going to rebase, but I'd be happy about any input, as I'm not very familiar with QT or the whole approach. - But it works, and I spent basically most of the time on testing.

**Comment by dexX7** [comment]
#29 is updated now.

**Comment by dexX7** [comment]
Seems fixed with the PR.
