### ISSUE TITLE
Log: disable all console prints

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#30]
Right now transaction informations are dumped into the console, as well as "#:  4, additional= 0".

This is annoying in my opinion, because that's what die actual log files are for. Just consider one would watch the console very closely to spot errors. No chance..

But I wanted to get your opinion on this first.

**Comment by zathras-crypto** [comment]
I'm happy for this to be cleaned up sure, the info is for debugging.  Here you go: https://github.com/zathras-crypto/mastercore/commit/70df6af996e21fa2c994a7c4a1614fc39814fd5b
