### ISSUE TITLE
Initialization: txindex default value

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#42]
To pick up the discussion of https://github.com/zathras-crypto/mastercore/commit/b1827ebba70110620718dfc2a4980f06498967dc#commitcomment-9862764 in particular:

The default value of `txindex` is currently - in contrast to Bitcoin Core's default - set to `true`.

This may turn into annoying behavior, if the user switches back and forth between Bitcoin Core and Omni Core.

It was proposed to revert to the original default value of a disabled transaction index, which appears to be safe, but it may result in the following situation:
1. User switches from Bitcoin Core to Omni Core
2. An error/warning is generated, because the transaction index is disabled
3. Manual user action is required to enable the indexing

**Comment by zathras-crypto** [comment]
I tend to think this is preferable (requiring user action) than a situation where every switch between Bitcoin Core and Omni Core causes a reindex in the scenario that a user has no `txindex` directive in their configuration (since starting Bitcoin Core will by default strip out the index, and starting Omni Core will by default add it back in).

A potential avenue is to flip the default back to `false` in line with default Bitcoin Core, and then amend our check so instead of saying "You need txindex=1 in your config" we could say "You need txindex=1 in your config, would you like us to add it?"

**Comment by dexX7** [comment]
We could skip the shutdown and restart by asking early, if the user wants to enable the txindex, but I don't see a way to change the config file or alike, so the actual issue isn't solved.

Wherever the release binaries are published, a simple tutorial with a few images to setup Omni Core would probably be of value anyway, so this is where an instruction to enable the txindex could be placed as well.

Speaking of: where is the release going to be published?

**Comment by zathras-crypto** [comment]
> Speaking of: where is the release going to be published?

We'll just follow that release process I've been asking for.... Oh wait... :p

Truth be told I genuinely don't know, perhaps OmniLayer.org?

**Comment by zathras-crypto** [comment]
> but I don't see a way to change the config file or alike

Can't be that hard to append a line of text to a flat file?  We already have a handle to the file and can read values from it, so wouldn't expect dropping in an extra line would be much effort - I can look into this _if_ that's the way we want to go.  Alternatively as you say it can just be left to a setup guide - speaking of, how does Armory do it?  They require an index, do they make the user manually adjust their conf?

**Comment by zathras-crypto** [comment]
Scratch that, seems I may have been given bad info - looking into Armory seems it scans raw blk?????.dat files and maintains it's own index, Bitcoin's txindex may be irrelevant in that context.

**Comment by dexX7** [comment]
> Can't be that hard to append a line of text to a flat file? We already have a handle to the file and can read values from it.

In `util.cpp` there is `boost::filesystem::path GetConfigFile()`, but there are some edge cases we'd probably need to cover, for example:
- Does the user really use a config file or started the client with CLI arguments? In the worst case we'd end up editing the default config file which has no relation to the actual execution.
- How about read/write permissions? The client could have read access, but no write access.

In my opinion, but I'm highly biased (!), probably unreasonably, it introduces additional risks. We don't touch the wallet directly, and neither mess with other core files.

**Comment by zathras-crypto** [comment]
They're valid edge cases - ack - I'm happy for it to go into some kind of setup guide, I guess the fact we haven't got anything like that leads me to try and handle everything on behalf of the user in code which is probably not the precedent we want to set :)

Considering this I'd say we need to flip it back to `false` as default and ask the user to add it to their config.

**Comment by dexX7** [comment]
Yup, sounds fine for me. It should be an info message instead of warning and in the best case link to a setup tutorial.

**Comment by dexX7** [comment]
Okay, PR pushed. This should be mentioned in the release notes though. :)
