### ISSUE TITLE
Release: find a home for binaries + further information

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#53]
As mentioned before, it would be great, if there were at least a central place to inform about the latest release and upcoming releases, especially for consensus critical updates.

Tutorials or setup guides would be ice on the cake, but to keep it minimal, a super simple landing page should include:
- version information
- links to binaries
- file checksums
- ideally GPG signatures
- ideally release notes and a change log

Ideally, such a landing page would be hosted at http://www.omnilayer.org/release or similar.

**Comment by zathras-crypto** [comment]
I think all these issues related to release should be raised on the main repo rather than my development branch - the main repo has a much broader audience for discussions like this :)

**Comment by dexX7** [comment]
https://github.com/mastercoin-MSC/mastercore/issues/291
